add api zoo_state and zoo_recv_timeout
ZHaskell/zoovisitor pull request #9
Opened 2021-03-27 03:56 UTC by Yu-zh

This fixes #2 and #3

2021-03-27 09:51 UTC, 4eUeP requested changes
Please add some tests for your function

2021-03-27 09:51 UTC, 4eUeP commented on src/ZooKeeper.hs
> +zooState :: T.ZHandle  -> IO CInt
This function should return `ZooKeeper.Types.ZooState` instead of `CInt`

2021-03-29 01:56 UTC, 4eUeP requested changes

2021-03-29 01:56 UTC, 4eUeP commented on src/ZooKeeper.hs
> +zooState = (I.ZooState <$>) . I.c_zoo_state
the `c_zoo_state` ffi can be directly written as  `c_zoo_state :: ZHandle -> IO ZooState`, so you do not need wrap it.

2021-03-29 02:01 UTC, Yu-zh commented on src/ZooKeeper.hs
> +zooState = (I.ZooState <$>) . I.c_zoo_state
Make sense

2021-03-29 02:34 UTC, 4eUeP approved these changes

2021-03-29 02:34 UTC, merged